odom_analyzer:
  ros__parameters:
    ground_truth_topic: /perfect/odom
    kinematic_topics:
      - /kinematics/odom
      - /camera_00/odom
      - /lidar_00/odom
      - /localization/odometry/filtered