/**:
  ros__parameters:
    qos: 1
    qos_image: 2
    qos_camera_info: 2
    use_sim_time: false
    subscribe_depth: false
    subscribe_rgb: false
    subscribe_rgbd: true
    subscribe_scan_cloud: true
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: true
    wait_for_transform: 0.2
    map_always_update: true
    Rtabmap/DetectionRate: "10"
    Rtabmap/TimeThr: "0"
    Mem/STMSize: "20"
    Mem/IncrementalMemory: "True"
    Mem/InitWMWithAllNodes: "False"
    Kp/MaxFeatures: "750"
    RGBD/NeighborLinkRefining: "True"
    Reg/Strategy: "2"
    Reg/Force3DoF: "false"
    Sterero/WinWidth: "15"
    Sterero/WinHeight: "3"
    Sterero/Iterations: "30"
    Sterero/DenseStrategy: "0"
    Grid/Sensor: "2"
    Grid/3D: "True"
    Grid/DepthDecimation: "4"
    Grid/RangeMin: "0.5"
    Grid/RangeMax: "5"
    Grid/FootprintLength: "1.5"
    Grid/FootprintWidth: "1.5"
    Grid/FootprintHeight: "1.5"
    Grid/MaxObstacleHeight: "0.2"
    Grid/MinGroundHeight: "0.0"
    Grid/MaxGroundHeight: "0.1"
    Grid/MaxGroundAngle: "35"
    Grid/FlatObstacleDetected: "True"
    Grid/FilteringRadious: "0.10"
    Grid/NoiseFilteringMinNeighbor: "4"
    GridGlobal/FootprintRadius: "0.75"
