main_compute:
  ros__parameters:
    # -- mode
    use_sim_time: true

    # -- 
    launch_description: false
    launch_camera_00: false
    launch_lidar_00: false
    launch_camera_00_odom: true
    launch_lidar_00_odom: true
    launch_localization: true
    launch_mapping: true

    # -- subsystem config files
    camera_00_config: "config/camera/camera.yaml"
    lidar_00_config: "config/lidar/lidar.yaml"
    camera_00_odom_config: "config/odometry/rgbd_odom.yaml"
    lidar_00_odom_config: "config/odometry/icp_odom.yaml"
    ekf_config: "config/odometry/ekf_filter.yaml"
    mapping_config: "config/mapping/mapping.yaml"

    # -- camera subsystem identifiers
    camera_package:      "rover_autonomy"
    camera_launch:       "luxonis_camera.launch.py"
    camera_ns:           "camera_00"
    camera_name:         "camera_00"
    camera_parent_frame: "sensor_mount_01_link"

    # -- lidar subsystem identifiers
    lidar_package:      "rover_autonomy"
    lidar_launch:       "ouster_lidar.launch.py"
    lidar_ns:           "lidar_00"
    lidar_name:         "lidar_00"
    lidar_parent_frame: "sensor_mount_00_link"

    # -- odometry subsystem identifiers
    camera_odom_package: "rover_autonomy"
    camera_odom_launch:  "rgbd_odometry.launch.py"
    camera_odom_ns:      "camera_00"

    lidar_odom_package:  "rover_autonomy"
    lidar_odom_launch:   "icp_odometry.launch.py"
    lidar_odom_ns:       "lidar_00"

    localization_package: "rover_autonomy"
    localization_launch:  "localization.launch.py"
    localization_type:    "ekf"

    mapping_package:      "rover_autonomy"
    mapping_launch:       "mapping.launch.py"
    delete_db_on_start:   true
