main_compute:
  ros__parameters:
    # -- mode
    use_sim_time: true

    # -- 
    launch_description: false
    launch_camera_00: true
    launch_camera_00_driver: true
    launch_camera_00_decompression: true
    launch_camera_00_post_processing: true
    launch_lidar_00: true
    launch_camera_00_odom: true
    launch_lidar_00_odom: true
    launch_localization: true
    launch_mapping: true
    launch_local_topography: true
    launch_global_topography: true
    launch_navigation: true

    # -- subsystem config files
    camera_00_config: "config/camera/camera.yaml"
    lidar_00_config: "config/lidar/lidar.yaml"
    camera_00_odom_config: "config/odometry/rgbd_odom.yaml"
    lidar_00_odom_config: "config/odometry/icp_odom.yaml"
    ekf_config: "config/odometry/ekf_filter.yaml"
    mapping_config: "config/mapping/mapping.yaml"
    navigation_config: "config/navigation/navigation.yaml"

    # -- camera subsystem identifiers
    camera_package:      "rover_autonomy"
    camera_driver_launch:          "camera_driver.launch.py"
    camera_decompression_launch:   "camera_decompression.launch.py"
    camera_post_processing_launch: "camera_post_processing.launch.py"
    camera_ns:           "camera_00"
    camera_name:         "camera_00"
    camera_parent_frame: "sensor_mount_01_link"

    camera_decompress_rgb: true
    camera_decompress_depth: true

    # -- lidar subsystem identifiers
    lidar_package:           "rover_autonomy"
    lidar_driver_launch:        "lidar_driver.launch.py"
    # lidar_decompression_launch: "lidar_decompression.launch.py"
    # lidar_processing_launch:    "lidar_processing.launch.py"
    lidar_ns:                "lidar_00"
    lidar_name:              "lidar_00"
    lidar_parent_frame:      "sensor_mount_00_link"

    # -- odometry subsystem identifiers
    camera_odom_package: "rover_autonomy"
    camera_odom_launch:  "rgbd_odometry.launch.py"
    camera_odom_ns:      "camera_00"

    lidar_odom_package:  "rover_autonomy"
    lidar_odom_launch:   "icp_odometry.launch.py"
    lidar_odom_ns:       "lidar_00"

    localization_package: "rover_autonomy"
    localization_launch:  "localization.launch.py"
    localization_type:    "ekf"

    mapping_package:      "rover_autonomy"
    mapping_launch:       "mapping.launch.py"
    mapping_ns:           "mapping"

    local_topography_package: "rover_topography"
    local_topography_launch:  "local_topography.launch.py"
    local_topography_ns:      ""
    
    global_topography_package: "rover_topography"
    global_topography_launch:  "global_topography.launch.py"
    global_topography_ns:      ""

    mapping_load_existing_db: false
    
    mapping_db_folder:    "~/.ros/rtabmap"
    mapping_db_file_name: "rtabmap.db"

    navigation_package:      "rover_autonomy"
    navigation_launch:       "navigation.launch.py"
    navigation_ns:           "navigation"
    navigation_autostart:    true
    navigation_use_composition: true
