/**:
  ros__parameters:
    camera:
      # i_usb_port_id: "1.4"
      # i_mx_id: "18443010C11C3F0E00"

      i_enable_ir: false
      i_laser_dot_brightness: 0

      i_pipeline_type: RGBD

      imu_from_descr: true
      i_enable_sync: true

    pipeline_gen:
      i_enable_imu: true
      i_enable_sync: true
      
      i_enable_diagnostics: false

    imu:
      i_message_type: IMU
      i_acc_freq: 400
      i_gyro_freq: 400
      i_sync_method: COPY

    rgb:
      i_fps: 30.0
      i_resolution: 1080p

      i_synced: true

      i_get_base_device_timestamp: false
      i_max_q_size: 30

      i_low_bandwidth: false
      # i_low_bandwidth_frame_freq: 30
      # i_low_bandwidth_quality: 50

      # i_publish_compressed: false
      # i_board_socket_id: 0

      i_publish_topic: true
    
    left:
      i_fps: 30.0
      i_resolution: 720P
      
      i_synced: true

      i_get_base_device_timestamp: false 
      i_max_q_size: 30

    right:
      i_fps: 30.0
      i_resolution: 720P
      
      i_synced: true

      i_get_base_device_timestamp: false 
      i_max_q_size: 30
    
    stereo:
      i_fps: 30.0
      i_resolution: 720P

      i_synced: true

      i_get_base_device_timestamp: false
      i_max_q_size: 30

      i_low_bandwidth: false
      # i_low_bandwidth_frame_freq: 30
      # i_low_bandwidth_quality: 50
      
      # i_publish_compressed: false
      # i_board_socket_id: 0

      i_enable_distortion_correction: true
      i_subpixel: false

      i_align_depth: true

      i_lr_check: false

      i_depth_preset: HIGH_ACCURACY
      i_publish_topic: true