bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    bt_loop_duration: 10
    filter_duration: 0.3
    default_server_timeout: 20
    default_cancel_timeout: 50
    wait_for_service_timeout: 1000
    introspection_mode: "disabled"
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    bt_search_directories:
      - $(find-pkg-share nav2_bt_navigator)/behavior_trees
    error_code_name_prefixes:
      - assisted_teleop
      - backup
      - compute_path
      - dock_robot
      - drive_on_heading
      - follow_object
      - follow_path
      - nav_thru_poses
      - nav_to_pose
      - route
      - spin
      - smoother
      - undock_robot
      - wait

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01 
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    path_handler_plugins: ["PathHandler"]
    use_realtime_priority: false

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      path_length_tolerance: 1.0
    PathHandler:
      plugin: "nav2_controller::FeasiblePathHandler"
      prune_distance: 2.0
      minimum_rotation_angle: 0.785
      
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 120
      model_dt: 0.05
      batch_size: 2000
      
      ax_max: 2.0
      ax_min: -2.0
      ay_max: 0.0   # Ackermann vehicles cannot translate sideways
      ay_min: 0.0   # Ackermann vehicles cannot translate sideways
      
      az_max: 1.5   
      
      vx_max: 1.0   
      vx_min: -1.0  
      vy_max: 0.0   # Ackermann vehicles cannot translate sideways
      vy_min: 0.0   # Ackermann vehicles cannot translate sideways
      
      wz_max: 1.5
      
      vx_std: 0.35
      vy_std: 0.0   # Ackermann vehicles cannot translate sideways
      wz_std: 0.35 
      
      iteration_count: 10
      temperature: 0.3
      
      # Hooking up the specific Ackermann Motion Model
      motion_model: "Ackermann"
      Ackermann:                 
        plugin: "nav2_mppi_controller::AckermannMotionModel"
        min_turning_r: 1.0 # Ensure this matches your hardware's minimum steering radius
        
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      TrajectoryValidator:
        plugin: "nav2_mppi_controller::TrajectoryValidator"
        collision_lookahead_time: 2.0
      critics:
        ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      ConstraintCritic:
        enabled: true
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_weight: 5.0
      CostCritic:
        enabled: true
        cost_weight: 3.81
        critical_cost: 300.0
      PathAlignCritic:
        enabled: true
        cost_weight: 8.0
      PathFollowCritic:
        enabled: true
        cost_weight: 5.0
      PathAngleCritic:
        enabled: true
        cost_weight: 2.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[ [0.60, 0.40], [0.60, -0.40], [-0.60, -0.40], [-0.60, 0.40] ]"
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.80
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /lidar_00/points
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      always_send_full_costmap: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[ [0.60, 0.40], [0.60, -0.40], [-0.60, -0.40], [-0.60, 0.40] ]"
      resolution: 0.05
      rolling_window: false
      width: 25
      height: 25
      origin_x: -12.5
      origin_y: -12.5
      track_unknown_space: false
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: pointcloud
        pointcloud:
          topic: /lidar_00/points
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          obstacle_max_range: 15.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.8
      always_send_full_costmap: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"
      downsample_costmap: false
      downsampling_factor: 1
      tolerance: 0.5
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 2.0
      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 1.0 # Ensure this matches your hardware
      reverse_penalty: 2.1

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    # Removed "spin" as Ackermann robots cannot turn in place
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"   
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "CLOSED_LOOP"
    # Nullified the middle value (y-axis) since you cannot strafe in Ackermann mode
    max_velocity: [1.0, 0.0, 1.8]
    min_velocity: [-1.0, 0.0, -1.8]
    max_accel: [2.0, 0.0, 1.5] 
    max_decel: [-2.0, 0.0, -1.5]
    odom_topic: "odom"

collision_monitor:
  ros__parameters:
    enabled: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "local_costmap/published_footprint"
      time_before_collision: 1.2
      enabled: true
    observation_sources: ["pointcloud"]
    pointcloud:
      type: "pointcloud"
      topic: "/lidar_00/points"
      min_height: 0.15
      max_height: 2.0
      enabled: true